services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KoninklijkeCollective\MyUserManagement\:
    resource: '../Classes/*'

  KoninklijkeCollective\MyUserManagement\Service\BackendUserControllerService:
    public: true
